# This is the Travis configuration for the building and deploying all lambda functions in this directory.
# Manual modifications to this file should be exceptionally rare.
# To add a new lambda, simply run ./create_new_lambda.sh

language: go

go:
  - 1.x

script:
  - go test -v
  - env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o index.bin-FIRST_LAMBDA_NAME FIRST_LAMBDA_NAME.go
  - zip -j index.bin-FIRST_LAMBDA_NAME.zip index.bin-FIRST_LAMBDA_NAME
  # [ADD_NEW_BUILD_HERE]

deploy:
  provider: lambda
  function_name: FIRST_LAMBDA_FULL_NAME
  region: PROJECT_REGION
  role: FIRST_LAMBDA_EXECUTOR_ROLE_ARN
  runtime: go1.x
  handler_name: "bin-FIRST_LAMBDA_NAME"
  access_key_id: TRAVIS_USER_ACCESS_KEY_ID
  # [ADD_NEW_LAMBDA_DEPLOYMENT_HERE]
